#!/usr/bin/env bash
# This script transfers a file from the client to a server using scp
# Assign parameters to the variables:
#+	file_path="$1"
#+	server_ip="$2"
#+	username="$3"
#+	ssh_key="$4"

# Display usage message if less than 4 parameters are provided
if [ $# -lt 4 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
# Transfer the file to the server's home directory using scp
#+ with strict host key checking disabled
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
