#!/usr/bin/env bash
# This script installs and configures Nginx with the following parameters:
#+	Nginx should be listening on port 80
#+	It should return a page containing "Hello World!" when queried
#++	You can’t use systemctl for restarting nginx

sudo apt-get update
sudo apt-get install -y nginx
sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

sudo service nginx restart
