#!/usr/bin/env bash
# This script installs and configures Nginx with the following parameters:
#+  Nginx should be listening on port 80
#+  It should return a page containing "Hello World!" when queried
#++  You can’t use systemctl for restarting nginx

sudo apt-get update
sudo apt-get install -y nginx
sudo mkdir -p /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello World!" | sudo tee /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" | sudo tee /etc/nginx/sites-available/default

# Check if Nginx is running, then restart it
if sudo service nginx status >/dev/null;
then
    sudo service nginx restart
else
    sudo service nginx start
fi
