#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# The custom header should be available on (web-01 and web-02)
# Get the hostname
var=$(hostname)

# Update apt package index
apt-get update -y

# Install Nginx
apt-get install nginx -y

# Create a simple index.html file
echo "Hello World!" > /usr/share/nginx/html/index.html

# Create a custom 404 page
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Define the new strings for sed substitution
new_string="error_page 404 /custom_404.html; \
location /redirect_me { \
return 301 \$scheme://www.google.com;"
new_string2="server {\n\tadd_header X-Served-By $var;"

# Modify the default Nginx configuration to include custom header
sudo sed -i -E "s/^[^#]+location \/ \{/$new_string/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server \{/$new_string2/" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
