#!/usr/bin/env bash
# A script that pings an ip address passed as an argument
#+ Accepts a string as an argument
#+ Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
#+ Ping the IP 5 times

#check if an argument is provided

if [ "$#" -eq 0 ];
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else

# Ping the ip address 5 times

	ping -c 5 "$1"
fi
