#!/usr/bin/env bash
# Configure an Nginx server to listen on port 80.

sudo sed -i '/listen\s*80;/d' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a \
    listen 80;' /etc/nginx/sites-available/default
sudo service nginx restart
