#!/usr/bin/env bash
# Configures Nginx to listen on port 80.

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
sudo kill "$(pgrep 'nginx' | head -n 1)"

