#!/usr/bin/env bash
# create the file "/var/run/myscript.pid" containing its PID

	echo $$ > /var/run/myscript.pid

# handle the SIGINT signal

interrupt()
{
	echo "Y U no love me?!"
}


# handle the SIGTERM and SIGQUIT signals

terminate()
{
	echo "I hate the kill command"
	rm -f /var/run/myscript.pid
	exit 0
}

# Trap the signals and call the related functions

trap terminate SIGTERM SIGQUIT
trap interrupt SIGINT

# display the message "To Infinity and beyond" indefinitely

while true
do
	echo "To infinity and beyond"
	sleep 2
done
