#!/usr/bin/env bash
# a while loop and IFS that displays the content of the /etc/passwd file

while IFS=: read -r username password uid gid info home shell;
do

# Display information about the user

	echo "The user $username is part of the $gid gang, lives in $home, and rides $shell."
	echo "USER ID's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
