#!/usr/bin/env bash
# A script that installs ufw firewall and sets up a few rules on web-01
# Block all incoming traffic except on the following TCP ports listed below
# 22 (SSH)
# 443 (HTTPS SSL)
# 80 (HTTP)
sudo apt-get update
sudo apt-get install ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
